<a href="https://colab.research.google.com/github/maverick98/Coursera/blob/master/mfml_assign2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from functools import reduce
from numpy.linalg import eig

In [9]:
def create_random_matrix(m=4,n=3):
    A = np.random.randint(low=0,high=10,size=(m, n))
    A=A.astype(float)
    return A
def transpose(A):
    m=A.shape[0]
    n=A.shape[1]
    A_T=np.zeros((n,m))
    for i in range(n):
        A_T[i]=A[:,i]
    return A_T
def multiply(A,B):
    if A.shape[1] != B.shape[0]:
       print("Illegal multiplication")
       return
    m=A.shape[0]
    n=A.shape[1]
    p=B.shape[1]
    C=np.zeros((m,p))
    for i in range(m):
        for k in range(p):
            for j in range(n):
                C[i][k]+=A[i][j]*B[j][k]

    return C
def subtract(A,B):
    if A.shape[0] != B.shape[0] or A.shape[1] != B.shape[1]:
       print("Illegal subtraction")
       return
    m=A.shape[0]
    n=A.shape[1]
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i][j]=A[i][j]-B[i][j]
    return C
def create_identity_matrix(n):
     I=np.zeros((n,n))
     for i in range(n):
         I[i][i]=1
     return I
def create_matrix(m,n):
    C=create_random_matrix(m,n)
    C_T=transpose(C)
    A=multiply(C_T,C)
    return A,C_T,C
def power_method(A, tol=1e-6, max_iter=1000):
    n = A.shape[0]
    x = np.random.rand(A.shape[0])
    x = x / np.linalg.norm(x)
    for i in range(max_iter):
        y = np.dot(A, x)
        x_new = y/np.linalg.norm(y)
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new
    return x,np.linalg.norm(np.dot(A,x))/np.linalg.norm(x)
def calculate_eigen_vectors_values(A):
    eigen_vectors=[]
    eigen_values=[]
    _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values)
    return eigen_vectors,eigen_values
def _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values):
    if A.shape[0] != A.shape[1]:
       print("Illegal operation")
       return
    if len(eigen_vectors) ==   A.shape[0]:
       return
    eigen_vector,eigen_value = power_method(A)
    eigen_vectors.append(eigen_vector)
    eigen_values.append(eigen_value)
    x=np.reshape(eigen_vector,(eigen_vector.shape[0],1))
    A_next=subtract(A,multiply(multiply(x,transpose(x)),A))
    _calculate_eigen_vectors_values(A_next,eigen_vectors,eigen_values)





In [7]:

A1,C_T,C=create_matrix(4,3)
print("C_T={}".format(C_T))
print("C={}".format(C))
print("A={}".format(A1))
w,v=eig(A1)
print('E-value:', w)
print('E-vector', v)


C_T=[[0. 3. 0. 8.]
 [3. 6. 4. 8.]
 [9. 8. 6. 1.]]
C=[[0. 3. 9.]
 [3. 6. 8.]
 [0. 4. 6.]
 [8. 8. 1.]]
A=[[ 73.  82.  32.]
 [ 82. 125. 107.]
 [ 32. 107. 182.]]
E-value: [291.26833116   1.3652255   87.36644334]
E-vector [[-0.33714043 -0.66070917 -0.67067109]
 [-0.62140694  0.69132397 -0.3686795 ]
 [-0.70724094 -0.29246291  0.64364253]]


In [10]:
eigen_vectors,eigen_values=calculate_eigen_vectors_values(A1)
print("eigen_vectors are {}".format(eigen_vectors))
print("eigen_values are {}".format(eigen_values))


eigen_vectors are [array([0.33714085, 0.62140717, 0.70724054]), array([ 0.67067105,  0.36867895, -0.6436429 ]), array([ 0.66070901, -0.69132406,  0.29246306])]
eigen_values are [291.26833116185674, 87.36644333783852, 1.3652255003347005]
