<a href="https://colab.research.google.com/github/maverick98/Coursera/blob/master/mfml_assign2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from functools import reduce
from numpy.linalg import eig

In [ ]:
def create_random_matrix(m=4,n=3):
    A = np.random.randint(low=0,high=10,size=(m, n))
    A=A.astype(float)
    return A
def transpose(A):
    m=A.shape[0]
    n=A.shape[1]
    A_T=np.zeros((n,m))
    for i in range(n):
        A_T[i]=A[:,i]
    return A_T
def multiply(A,B):
    if A.shape[1] != B.shape[0]:
       print("Illegal multiplication")
       return
    m=A.shape[0]
    n=A.shape[1]
    p=B.shape[1]
    C=np.zeros((m,p))
    for i in range(m):
        for k in range(p):
            for j in range(n):
                C[i][k]+=A[i][j]*B[j][k]

    return C
def subtract(A,B):
    if A.shape[0] != B.shape[0] or A.shape[1] != B.shape[1]:
       print("Illegal subtraction")
       return
    m=A.shape[0]
    n=A.shape[1]
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i][j]=A[i][j]-B[i][j]
    return C
def create_identity_matrix(n):
     I=np.zeros((n,n))
     for i in range(n):
         I[i][i]=1
     return I
def create_matrix(m,n):
    C=create_random_matrix(m,n)
    C_T=transpose(C)
    A=multiply(C_T,C)
    return A,C_T,C
def power_method(A, tol=1e-6, max_iter=1000):
    n = A.shape[0]
    x = np.random.rand(A.shape[0])
    x = x / np.linalg.norm(x)
    for i in range(max_iter):
        y = np.dot(A, x)
        x_new = y/np.linalg.norm(y)
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new
    return x,np.linalg.norm(np.dot(A,x))/np.linalg.norm(x)
def calculate_eigen_vectors_values(A):
    eigen_vectors=[]
    eigen_values=[]
    _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values)
    return eigen_vectors,eigen_values
def _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values):
    if A.shape[0] != A.shape[1]:
       print("Illegal operation")
       return
    if len(eigen_vectors) ==   A.shape[0]:
       return
    eigen_vector,eigen_value = power_method(A)
    eigen_vectors.append(eigen_vector)
    eigen_values.append(eigen_value)
    x=np.reshape(eigen_vector,(eigen_vector.shape[0],1))
    A_next=subtract(A,multiply(multiply(x,transpose(x)),A))
    _calculate_eigen_vectors_values(A_next,eigen_vectors,eigen_values)





In [ ]:

A1,C_T,C=create_matrix(4,3)
print("C_T={}".format(C_T))
print("C={}".format(C))
print("A={}".format(A1))
w,v=eig(A1)
print('E-value:', w)
print('E-vector', v)


C_T=[[0. 1. 7. 3.]
 [8. 6. 8. 8.]
 [9. 9. 1. 5.]]
C=[[0. 8. 9.]
 [1. 6. 9.]
 [7. 8. 1.]
 [3. 8. 5.]]
A=[[ 59.  86.  31.]
 [ 86. 228. 174.]
 [ 31. 174. 188.]]
E-value: [404.17913984  68.62507895   2.19578121]
E-vector [[-0.24062864 -0.71043994  0.66134178]
 [-0.73897404 -0.30766595 -0.59938221]
 [-0.6292974   0.63294294  0.45096343]]


In [ ]:
eigen_vectors,eigen_values=calculate_eigen_vectors_values(A1)
print("eigen_vectors are {}".format(eigen_vectors))
print("eigen_values are {}".format(eigen_values))


eigen_vectors are [array([0.24062893, 0.73897417, 0.62929715]), array([ 0.71044007,  0.30766544, -0.63294303]), array([ 0.66134154, -0.59938231,  0.45096365])]
eigen_values are [404.1791398432546, 68.62507894658683, 2.195781210184915]


In [ ]:

def f(x, y):
    return 10*x**4 - 20*x**2*y + x**2 + 10*y**2 - 2*x + 1

def grad_f(x, y):
    grad_x = 40*x**3 - 40*x*y + 2*x - 2
    grad_y = -20*x**2 + 20*y
    return np.array([grad_x, grad_y])

def armijo_rule(f, grad_f_x_y, x_y, g_t, alpha=1, beta=0.5, mu=0.1):
    x=x_y[0]
    y=x_y[1]
    while f(x + alpha * g_t[0],y + alpha * g_t[1]) > f(x,y) + mu * alpha * np.dot(grad_f_x_y, g_t):
        alpha *= beta
    return alpha

def gradient_descent_armijo(f, grad_f, initial_point, tolerance=1e-6, max_iterations=1000):
    x_y = np.array(initial_point)
    for _ in range(max_iterations):
        gradient = grad_f(x_y[0],x_y[1])
        if np.linalg.norm(gradient) < tolerance:
            break
        step_size = armijo_rule(f, gradient, x_y, -gradient)
        x_y -= step_size * gradient
    return x_y

# Initial point for optimization
initial_point = [0.0, 0.0]

# Perform gradient descent with Armijo rule
result = gradient_descent_armijo(f, grad_f, initial_point)

print("Stationary point found at (x, y) =", result)
print("Value of f(x, y) at the stationary point:", f(result[0],result[1]))


Stationary point found at (x, y) = [0.99997957 0.99995871]
Value of f(x, y) at the stationary point: 4.192415303805319e-10
