<a href="https://colab.research.google.com/github/maverick98/Coursera/blob/master/mfml_assign2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
from functools import reduce
from numpy.linalg import eig

In [18]:
def create_random_matrix(m=4,n=3):
    A = np.random.randint(low=0,high=10,size=(m, n))
    A=A.astype(float)
    return A
def transpose(A):
    m=A.shape[0]
    n=A.shape[1]
    A_T=np.zeros((n,m))
    for i in range(n):
        A_T[i]=A[:,i]
    return A_T
def multiply(A,B):
    if A.shape[1] != B.shape[0]:
       print("Illegal multiplication")
       return
    m=A.shape[0]
    n=A.shape[1]
    p=B.shape[1]
    C=np.zeros((m,p))
    for i in range(m):
        for k in range(p):
            for j in range(n):
                C[i][k]+=A[i][j]*B[j][k]

    return C
def subtract(A,B):
    if A.shape[0] != B.shape[0] or A.shape[1] != B.shape[1]:
       print("Illegal subtraction")
       return
    m=A.shape[0]
    n=A.shape[1]
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i][j]=A[i][j]-B[i][j]
    return C
def create_identity_matrix(n):
     I=np.zeros((n,n))
     for i in range(n):
         I[i][i]=1
     return I
def create_matrix(m,n):
    C=create_random_matrix(m,n)
    C_T=transpose(C)
    A=multiply(C_T,C)
    return A,C_T,C
def power_method(A, tol=1e-6, max_iter=1000):
    n = A.shape[0]
    x = np.random.rand(A.shape[0])
    x = x / np.linalg.norm(x)
    for i in range(max_iter):
        y = np.dot(A, x)
        x_new = y/np.linalg.norm(y)
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new
    return x,np.linalg.norm(np.dot(A,x))/np.linalg.norm(x)
def calculate_eigen_vectors_values(A):
    eigen_vectors=[]
    eigen_values=[]
    _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values)
    return eigen_vectors,eigen_values
def _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values):
    if A.shape[0] != A.shape[1]:
       print("Illegal operation")
       return
    if len(eigen_vectors) ==   A.shape[0]:
       return
    eigen_vector,eigen_value = power_method(A)
    eigen_vectors.append(eigen_vector)
    eigen_values.append(eigen_value)
    x=np.reshape(eigen_vector,(eigen_vector.shape[0],1))
    A_next=subtract(A,multiply(multiply(x,transpose(x)),A))
    _calculate_eigen_vectors_values(A_next,eigen_vectors,eigen_values)





In [19]:

A1,C_T,C=create_matrix(4,3)
print("C_T={}".format(C_T))
print("C={}".format(C))
print("A={}".format(A1))
w,v=eig(A1)
print('E-value:', w)
print('E-vector', v)


C_T=[[1. 5. 6. 4.]
 [2. 9. 3. 3.]
 [8. 1. 2. 5.]]
C=[[1. 2. 8.]
 [5. 9. 1.]
 [6. 3. 2.]
 [4. 3. 5.]]
A=[[ 78.  77.  45.]
 [ 77. 103.  46.]
 [ 45.  46.  94.]]
E-value: [205.50175864  12.13248498  57.36575638]
E-vector [[-0.57019539 -0.78011654 -0.25747893]
 [-0.6523904   0.62047638 -0.43519631]
 [-0.49926344  0.08017015  0.86273331]]


In [20]:
eigen_vectors,eigen_values=calculate_eigen_vectors_values(A1)
print("eigen_vectors are {}".format(eigen_vectors))
print("eigen_values are {}".format(eigen_values))


eigen_vectors are [array([0.57019522, 0.65239011, 0.49926402]), array([ 0.25747898,  0.43519702, -0.86273294]), array([-0.78011665,  0.62047619,  0.08017052])]
eigen_values are [205.5017586364409, 57.36575638434446, 12.132484979242557]


In [29]:

def f(x, y):
    return 10*x**4 - 20*x**2*y + x**2 + 10*y**2 - 2*x + 1

def grad_f(x, y):
    grad_x = 40*x**3 - 40*x*y + 2*x - 2
    grad_y = -20*x**2 + 20*y
    return np.array([grad_x, grad_y])

def armijo_rule(f, grad_f_x_y, x_y, g_t, alpha=1, beta=0.5, mu=0.1):
    x=x_y[0]
    y=x_y[1]
    while f(x + alpha * g_t[0],y + alpha * g_t[1]) > f(x,y) + mu * alpha * np.dot(grad_f_x_y, g_t):
        alpha *= beta
    return alpha

def gradient_descent_armijo(f, grad_f, initial_point, tolerance=1e-6, max_iterations=1000):
    x_y = np.array(initial_point)
    for _ in range(max_iterations):
        gradient = grad_f(x_y[0],x_y[1])
        if np.linalg.norm(gradient) < tolerance:
            break
        step_size = armijo_rule(f, gradient, x_y, -gradient)
        x_y -= step_size * gradient
    return x_y

# Initial point for optimization
initial_point = [0.0, 0.0]

# Perform gradient descent with Armijo rule
result = gradient_descent_armijo(f, grad_f, initial_point)

print("Stationary point found at (x, y) =", result)
print("Value of f(x, y) at the stationary point:", f(result[0],result[1]))


Stationary point found at (x, y) = [0.99997957 0.99995871]
Value of f(x, y) at the stationary point: 4.192415303805319e-10
