<a href="https://colab.research.google.com/github/maverick98/Coursera/blob/master/mfml_assign2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
from numpy.linalg import eig

In [52]:
def create_random_matrix(m=4,n=3):
    A = np.random.randint(low=0,high=10,size=(m, n))
    A=A.astype(float)
    return A
def transpose(A):
    m=A.shape[0]
    n=A.shape[1]
    A_T=np.zeros((n,m))
    for i in range(n):
        A_T[i]=A[:,i]
    return A_T
def multiply(A,B):
    if A.shape[1] != B.shape[0]:
       print("Illegal multiplication")
       return
    m=A.shape[0]
    n=A.shape[1]
    p=B.shape[1]
    C=np.zeros((m,p))
    for i in range(m):
        for k in range(p):
            for j in range(n):
                C[i][k]+=A[i][j]*B[j][k]

    return C
def subtract(A,B):
    if A.shape[0] != B.shape[0] or A.shape[1] != B.shape[1]:
       print("Illegal subtraction")
       return
    m=A.shape[0]
    n=A.shape[1]
    C=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            C[i][j]=A[i][j]-B[i][j]
    return C

def create_matrix(m,n):
    C=create_random_matrix(m,n)
    C_T=transpose(C)
    A=multiply(C_T,C)
    return A,C_T,C
def power_method(A, tol=1e-6, max_iter=1000):
    print('***************Starting Power Method for A={}****************'.format(A))
    n = A.shape[0]
    x = np.random.rand(A.shape[0])
    x = x / np.linalg.norm(x)
    lambdaa=None
    for i in range(max_iter):
        y = np.dot(A, x)
        x_new = y/np.linalg.norm(y)
        if np.linalg.norm(x_new - x) < tol:
            print('Stopping Power method at {}th iteration as the difference is below tolerance {}'.format(i,tol))
            print('***************Finished Power Method for A={}****************'.format(A))
            print('    ')
            break
        x = x_new
        lambdaa=np.linalg.norm(np.dot(A,x))/np.linalg.norm(x)
        if i <= 10:
           print('At {}th iteration ,  x is {}'.format(i,x))
           print('At {}th iteration ,  lambda is {}'.format(i,lambdaa))
           print('------')
    return x,lambdaa
def calculate_eigen_vectors_values(A):
    eigen_vectors=[]
    eigen_values=[]
    _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values)
    return eigen_vectors,eigen_values
def _calculate_eigen_vectors_values(A,eigen_vectors,eigen_values):
    if A.shape[0] != A.shape[1]:
       print("Illegal operation")
       return
    if len(eigen_vectors) ==   A.shape[0]:
       return
    eigen_vector,eigen_value = power_method(A)
    eigen_vectors.append(eigen_vector)
    eigen_values.append(eigen_value)
    x=np.reshape(eigen_vector,(eigen_vector.shape[0],1))
    A_next=subtract(A,multiply(multiply(x,transpose(x)),A))
    _calculate_eigen_vectors_values(A_next,eigen_vectors,eigen_values)





In [53]:

A1,C_T,C=create_matrix(4,3)
print("C_T={}".format(C_T))
print("C={}".format(C))
print("A={}".format(A1))
w,v=eig(A1)
print('E-value:', w)
print('E-vector', v)


C_T=[[9. 8. 0. 0.]
 [7. 2. 6. 9.]
 [5. 4. 9. 0.]]
C=[[9. 7. 5.]
 [8. 2. 4.]
 [0. 6. 9.]
 [0. 9. 0.]]
A=[[145.  79.  77.]
 [ 79. 170.  97.]
 [ 77.  97. 122.]]
E-value: [316.33854349  77.8996263   42.76183021]
E-vector [[ 0.54012436  0.79890113 -0.26461797]
 [ 0.64773716 -0.59537599 -0.47535671]
 [ 0.53731019 -0.08534885  0.83905502]]


In [54]:
eigen_vectors,eigen_values=calculate_eigen_vectors_values(A1)
print("eigen_vectors are {}".format(eigen_vectors))
print("eigen_values are {}".format(eigen_values))


***************Starting Power Method for A=[[145.  79.  77.]
 [ 79. 170.  97.]
 [ 77.  97. 122.]]****************
At 0th iteration ,  x is [0.64489204 0.60676253 0.46470797]
At 0th iteration ,  lambda is 313.6434991989911
------
At 1th iteration ,  x is [0.56505586 0.63502918 0.52673505]
At 1th iteration ,  lambda is 316.20498599704666
------
At 2th iteration ,  x is [0.54603505 0.64416338 0.53562978]
At 2th iteration ,  lambda is 316.33102468321033
------
At 3th iteration ,  x is [0.54154499 0.64679281 0.53701777]
At 3th iteration ,  lambda is 316.3380982280711
------
At 4th iteration ,  x is [0.54046928 0.64749569 0.5372544 ]
At 4th iteration ,  lambda is 316.33851668825304
------
At 5th iteration ,  x is [0.54020862 0.64767648 0.53729863]
At 5th iteration ,  lambda is 316.33854187223756
------
At 6th iteration ,  x is [0.54014502 0.64772205 0.53730764]
At 6th iteration ,  lambda is 316.33854339591335
------
At 7th iteration ,  x is [0.54012943 0.64773342 0.5373096 ]
At 7th iteration

In [55]:

def f(x, y):
    return 10*x**4 - 20*x**2*y + x**2 + 10*y**2 - 2*x + 1

def grad_f(x, y):
    grad_x = 40*x**3 - 40*x*y + 2*x - 2
    grad_y = -20*x**2 + 20*y
    return np.array([grad_x, grad_y])

def armijo_rule(f, grad_f_x_y, x_y, g_t, alpha=1, beta=0.5, mu=0.1):
    x=x_y[0]
    y=x_y[1]
    while f(x + alpha * g_t[0],y + alpha * g_t[1]) > f(x,y) + mu * alpha * np.dot(grad_f_x_y, g_t):
        alpha *= beta
    return alpha

def gradient_descent_armijo(f, grad_f, initial_point, tolerance=1e-6, max_iterations=1000):
    x_y = np.array(initial_point)
    for _ in range(max_iterations):
        gradient = grad_f(x_y[0],x_y[1])
        if np.linalg.norm(gradient) < tolerance:
            break
        step_size = armijo_rule(f, gradient, x_y, -gradient)
        x_y -= step_size * gradient
    return x_y

# Initial point for optimization
initial_point = [0.0, 0.0]

# Perform gradient descent with Armijo rule
result = gradient_descent_armijo(f, grad_f, initial_point)

print("Stationary point found at (x, y) =", result)
print("Value of f(x, y) at the stationary point:", f(result[0],result[1]))


Stationary point found at (x, y) = [0.99997957 0.99995871]
Value of f(x, y) at the stationary point: 4.192415303805319e-10
